const data = [
  {
    bingoItem: "Taylor Swift",
    type: "Album",
    listOfMusics: [
      "Tim McGraw",
      "Picture To Burn",
      "A Place In This World",
      "Cold As You",
      "The Outside",
      "Stay Beautiful",
      "Should’ve Said No",
      "Mary’s Song (Oh My My My)",
      "Our Song",
      "I’m Only Me When I’m With You",
      "Deluxe)",
      "Invisible",
      "Deluxe)",
      "A Perfectly Good Heart",
      "Deluxe)",
      "Teardrops on My Guitar Pop Version",
      "Taylor Swift’s first phone call with Tim McGraw (Deluxe)",
      "I Heart ? (Best Buy Digital Download)",
    ],
  },
  {
    bingoItem: "Fearless",
    type: "Album",
    listOfMusics: [
      "Breathe",
      "Bye Bye Baby",
      "Change",
      "Come In With The Rain",
      "Don't You",
      "Fearless",
      "Fifteen",
      "Forever & Always",
      "Hey Stephen",
      "Jump Then Fall",
      "Love Story",
      "Mr. Perfectly Fine",
      "Superstar",
      "Tell Me Why",
      "That's When",
      "The Best Day",
      "The Other Side of the Door",
      "The Way I Loved You",
      "Today Was a Fairytale",
      "Untouchable",
      "We Were Happy",
      "White Horse",
      "You All Over Me",
      "You Belong With Me",
      "You're Not Sorry",
    ],
  },
  {
    bingoItem: "Speak Now",
    type: "Album",
    listOfMusics: [
      "Back To December",
      "Better Than Revenge",
      "Castles Crumbling",
      "Dear John",
      "Electric Touch",
      "Enchanted",
      "Foolish One",
      "Haunted",
      "I Can See You",
      "Innocent",
      "Last Kiss",
      "Long Live",
      "Mean",
      "Mine",
      "Never Grow Up",
      "Ours",
      "Sparks Fly",
      "Speak Now",
      "Superman",
      "The Story Of Us",
      "Timeless",
      "When Emma Falls in Love",
    ],
  },
  {
    bingoItem: "Red",
    type: "Album",
    listOfMusics: [
      "22",
      "All Too Well (10 Minute Version)",
      "All Too Well",
      "Babe",
      "Begin Again",
      "Better Man",
      "Come Back...Be Here",
      "Everything Has Changed",
      "Forever Winter",
      "Girl At Home",
      "Holy Ground",
      "I Almost Do",
      "I Bet You Think About Me",
      "I Knew You Were Trouble",
      "Message In A Bottle",
      "Nothing New",
      "Red",
      "Ronan",
      "Run",
      "Sad Beautiful Tragic",
      "Starlight",
      "State of Grace",
      "Stay Stay Stay",
      "The Last Time",
      "The Lucky One",
      "The Moment I Knew",
      "The Very First Night",
      "Treacherous",
      "We Are Never Ever Getting Back Together",
    ],
  },
  {
    bingoItem: "1989",
    type: "Album",
    listOfMusics: [
      "All You Had To Do Was Stay",
      "Bad Blood",
      "Blank Space",
      "Clean",
      "How You Get The Girl",
      "I Know Places",
      "Is It Over Now?",
      "I Wish You Would",
      "New Romantics",
      "Now That We Don't Talk",
      "Out Of The Woods",
      "Say Don't Go",
      "Shake It Off",
      "Slut!",
      "Style",
      "Suburban Legends",
      "Sweeter Than Fiction",
      "This Love",
      "Welcome To New York",
      "Wildest Dreams",
      "Wonderland",
      "You Are In Love",
      "Bad Blood (Remix)",
    ],
  },
  {
    bingoItem: "Reputation",
    type: "Album",
    listOfMusics: [
      "Call It What You Want",
      "Dancing With Our Hands Tied",
      "Delicate",
      "Don't Blame Me",
      "Dress",
      "End Game",
      "Getaway Car",
      "Gorgeous",
      "I Did Something Bad",
      "King of My Heart",
      "Look What You Made Me Do",
      "New Year's Day",
      "So It Goes...",
      "This Is Why We Can't Have Nice Things",
    ],
  },
  {
    bingoItem: "Lover",
    type: "Album",
    listOfMusics: [
      "Afterglow",
      "Cornelia Street",
      "Cruel Summer",
      "Daylight",
      "Death By A Thousand Cuts",
      "False God",
      "I Forgot That You Existed",
      "I Think He Knows",
      "It's Nice To Have A Friend",
      "London Boy",
      "Lover",
      "ME!",
      "Miss Americana & The Heartbreak Prince",
      "Paper Rings",
      "Soon You'll Get Better",
      "The Archer",
      "The Man",
      "You Need To Calm Down",
    ],
  },
  {
    bingoItem: "Folklore",
    type: "Album",
    listOfMusics: [
      "august",
      "betty",
      "cardigan",
      "epiphany",
      "exile",
      "hoax",
      "illicit affairs",
      "invisible string",
      "mad woman",
      "mirrorball",
      "my tears ricochet",
      "peace",
      "seven",
      "the 1",
      "the last great american dynasty",
      "this is me trying",
    ],
  },
  {
    bingoItem: "Evermore",
    type: "Album",
    listOfMusics: [
      "champagne problems",
      "closure",
      "coney island",
      "cowboy like me",
      "dorothea",
      "evermore",
      "gold rush",
      "happiness",
      "ivy",
      "long story short",
      "marjorie",
      "no body, no crime",
      "'tis the damn season",
      "tolerate it",
      "willow",
    ],
  },
  {
    bingoItem: "Midnights",
    type: "Album",
    listOfMusics: [
      "Anti-Hero",
      "Bejeweled",
      "Bigger Than The Whole Sky",
      "Dear Reader",
      "Glitch",
      "High Infidelity",
      "Karma",
      "Labyrinth",
      "Lavender Haze",
      "Maroon",
      "Mastermind",
      "Midnight Rain",
      "Paris",
      "Question...?",
      "Snow On The Beach",
      "Sweet Nothing",
      "The Great War",
      "Vigilante Shit",
      "Would've Could've Should've",
      "You're On Your Own Kid",
    ],
  },
  {
    bingoItem: "Joe Jonas",
    type: "Boyfriend",
    listOfMusics: ["Forever & Always", "Last Kiss"],
  },
  {
    bingoItem: "Taylor Lautner",
    type: "Boyfriend",
    listOfMusics: ["Back to December"],
  },
  {
    bingoItem: "John Mayer",
    type: "Boyfriend",
    listOfMusics: [
      "Dear John",
      "The Story of Us",
      "Haunted",
      "Would've Could've Should've",
    ],
  },
  {
    bingoItem: "Jake Gyllenhaal",
    type: "Boyfriend",
    listOfMusics: [
      "We Are Never Ever Getting Back Together",
      "The Last Time",
      "All Too Well",
      "State of Grace",
    ],
  },
  {
    bingoItem: "Conor Kennedy",
    type: "Boyfriend",
    listOfMusics: ["Begin Again"],
  },
  {
    bingoItem: "Harry Styles",
    type: "Boyfriend",
    listOfMusics: [
      "Style",
      "Out of the Woods",
      "Now That We don't talk",
      "Is it over now?",
    ],
  },
  {
    bingoItem: "Joe Alwyn",
    type: "Boyfriend",
    listOfMusics: [
      "Delicate",
      "Call It What You Want",
      "...Ready for It?",
      "Gorgeous",
      "King of My Heart",
      "Dancing With Our Hands Tied",
      "Dress",
      "New Year's Day",
      "London Boy",
      "Cornelia Street",
    ],
  },
  {
    bingoItem: "Green",
    type: "Colors",
    listOfMusics: [
      "Tim McGraw",
      "Picture To Burn",
      "A Place In This World",
      "Cold As You",
      "The Outside",
      "Stay Beautiful",
      "Should’ve Said No",
      "Mary’s Song (Oh My My My)",
      "Our Song",
      "I’m Only Me When I’m With You",
      "Deluxe)",
      "Invisible",
      "A Perfectly Good Heart",
      "Teardrops on My Guitar Pop Version (2008)",
      "Taylor Swift’s first phone call with Tim McGraw",
      "I Heart ?",
    ],
  },
  {
    bingoItem: "Yellow",
    type: "Colors",
    listOfMusics: [
      "Breathe",
      "Bye Bye Baby",
      "Change",
      "Come In With The Rain",
      "Don't You",
      "Fearless",
      "Fifteen",
      "Forever & Always",
      "Hey Stephen",
      "Jump Then Fall",
      "Love Story",
      "Mr. Perfectly Fine",
      "Superstar",
      "Tell Me Why",
      "That's When",
      "The Best Day",
      "The Other Side of the Door",
      "The Way I Loved You",
      "Today Was a Fairytale",
      "Untouchable",
      "We Were Happy",
      "White Horse",
      "You All Over Me",
      "You Belong With Me",
      "You're Not Sorry",
    ],
  },
  {
    bingoItem: "Purple",
    type: "Colors",
    listOfMusics: [
      "Back To December",
      "Better Than Revenge",
      "Castles Crumbling",
      "Dear John",
      "Electric Touch",
      "Enchanted",
      "Foolish One",
      "Haunted",
      "I Can See You",
      "Innocent",
      "Last Kiss",
      "Long Live",
      "Mean",
      "Mine",
      "Never Grow Up",
      "Ours",
      "Sparks Fly",
      "Speak Now",
      "Superman",
      "The Story Of Us",
      "Timeless",
      "When Emma Falls in Love",
    ],
  },
  {
    bingoItem: "Red",
    type: "Colors",
    listOfMusics: [
      "22",
      "All Too Well (10 Minute Version)",
      "All Too Well",
      "Babe",
      "Begin Again",
      "Better Man",
      "Come Back...Be Here",
      "Everything Has Changed",
      "Forever Winter",
      "Girl At Home",
      "Holy Ground",
      "I Almost Do",
      "I Bet You Think About Me",
      "I Knew You Were Trouble",
      "Message In A Bottle",
      "Nothing New",
      "Red",
      "Ronan",
      "Run",
      "Sad Beautiful Tragic",
      "Starlight",
      "State of Grace",
      "Stay Stay Stay",
      "The Last Time",
      "The Lucky One",
      "The Moment I Knew",
      "The Very First Night",
      "Treacherous",
      "We Are Never Ever Getting Back Together",
    ],
  },
  {
    bingoItem: "Blue",
    type: "Colors",
    listOfMusics: [
      "All You Had To Do Was Stay",
      "Bad Blood",
      "Blank Space",
      "Clean",
      "How You Get The Girl",
      "I Know Places",
      "Is It Over Now?",
      "I Wish You Would",
      "New Romantics",
      "Now That We Don't Talk",
      "Out Of The Woods",
      "Say Don't Go",
      "Shake It Off",
      "Slut!",
      "Style",
      "Suburban Legends",
      "Sweeter Than Fiction",
      "This Love",
      "Welcome To New York",
      "Wildest Dreams",
      "Wonderland",
      "You Are In Love",
      "Bad Blood (Remix)",
    ],
  },
  {
    bingoItem: "Black",
    type: "Colors",
    listOfMusics: [
      "Call It What You Want",
      "Dancing With Our Hands Tied",
      "Delicate",
      "Don't Blame Me",
      "Dress",
      "End Game",
      "Getaway Car",
      "Gorgeous",
      "I Did Something Bad",
      "King of My Heart",
      "Look What You Made Me Do",
      "New Year's Day",
      "So It Goes...",
      "This Is Why We Can't Have Nice Things",
    ],
  },
  {
    bingoItem: "Pink",
    type: "Colors",
    listOfMusics: [
      "Afterglow",
      "Cornelia Street",
      "Cruel Summer",
      "Daylight",
      "Death By A Thousand Cuts",
      "False God",
      "I Forgot That You Existed",
      "I Think He Knows",
      "It's Nice To Have A Friend",
      "London Boy",
      "Lover",
      "ME!",
      "Miss Americana & The Heartbreak Prince",
      "Paper Rings",
      "Soon You'll Get Better",
      "The Archer",
      "The Man",
      "You Need To Calm Down",
    ],
  },
  {
    bingoItem: "Gray",
    type: "Colors",
    listOfMusics: [
      "august",
      "betty",
      "cardigan",
      "epiphany",
      "exile",
      "hoax",
      "illicit affairs",
      "invisible string",
      "mad woman",
      "mirrorball",
      "my tears ricochet",
      "peace",
      "seven",
      "the 1",
      "the last great american dynasty",
      "this is me trying",
    ],
  },
  {
    bingoItem: "Brown",
    type: "Colors",
    listOfMusics: [
      "champagne problems",
      "closure",
      "coney island",
      "cowboy like me",
      "dorothea",
      "evermore",
      "gold rush",
      "happiness",
      "ivy",
      "long story short",
      "marjorie",
      "no body, no crime",
      "'tis the damn season",
      "tolerate it",
      "willow",
    ],
  },
  {
    bingoItem: "Dark blue",
    type: "Colors",
    listOfMusics: [
      "Anti-Hero",
      "Bejeweled",
      "Bigger Than The Whole Sky",
      "Dear Reader",
      "Glitch",
      "High Infidelity",
      "Karma",
      "Labyrinth",
      "Lavender Haze",
      "Maroon",
      "Mastermind",
      "Midnight Rain",
      "Paris",
      "Question...?",
      "Snow On The Beach",
      "Sweet Nothing",
      "The Great War",
      "Vigilante Shit",
      "Would've Could've Should've",
      "You're On Your Own Kid",
    ],
  },
  {
    bingoItem: "Ed Sheeran",
    type: "Featuring song",
    listOfMusics: [
      "Everything Has Changed",
      "Run",
      "The Joker And The Queen",
      "Endgame",
    ],
  },
  {
    bingoItem: "Bon Iver",
    type: "Featuring song",
    listOfMusics: ["exile", "evermore"],
  },
  {
    bingoItem: "Brendon Urie",
    type: "Featuring song",
    listOfMusics: ["ME!"],
  },
  {
    bingoItem: "The Civil Wars",
    type: "Featuring song",
    listOfMusics: ["Safe & Sound"],
  },
  {
    bingoItem: "Gary Lightbody",
    type: "Featuring song",
    listOfMusics: ["The Last Time"],
  },
  {
    bingoItem: "Kendrick Lamar",
    type: "Featuring song",
    listOfMusics: ["Badblood"],
  },
  {
    bingoItem: "Zayn Malik",
    type: "Featuring song",
    listOfMusics: ["I Don`t Wanna Live Forever"],
  },
  {
    bingoItem: "HAIM",
    type: "Featuring song",
    listOfMusics: ["no body, no crime", "Gasoline"],
  },
  {
    bingoItem: "The Chicks",
    type: "Featuring song",
    listOfMusics: ["Soon You`ll Get Better"],
  },
  {
    bingoItem: "Colbie Caillat",
    type: "Featuring song",
    listOfMusics: ["Breathe"],
  },
  {
    bingoItem: "Keith Urban",
    type: "Featuring song",
    listOfMusics: ["That`s When"],
  },
  {
    bingoItem: "Maren Morris",
    type: "Featuring song",
    listOfMusics: ["You All Over Me"],
  },
  {
    bingoItem: "B.o.B",
    type: "Featuring song",
    listOfMusics: ["Both of Us"],
  },
  {
    bingoItem: "Future",
    type: "Featuring song",
    listOfMusics: ["Endgame"],
  },
  {
    bingoItem: "Hailey Williams",
    type: "Featuring song",
    listOfMusics: ["Castles Crumbling"],
  },
  {
    bingoItem: "Fall Out Boy",
    type: "Featuring song",
    listOfMusics: ["Eletric Touch"],
  },
  {
    bingoItem: "Grammy",
    type: "Included in an album who won",
    listOfMusics: [
      "Breathe",
      "Bye Bye Baby",
      "Change",
      "Come In With The Rain",
      "Don't You",
      "Fearless",
      "Fifteen",
      "Forever & Always",
      "Hey Stephen",
      "Jump Then Fall",
      "Love Story",
      "Mr. Perfectly Fine",
      "Superstar",
      "Tell Me Why",
      "That's When",
      "The Best Day",
      "The Other Side of the Door",
      "The Way I Loved You",
      "Today Was a Fairytale",
      "Untouchable",
      "We Were Happy",
      "White Horse",
      "You All Over Me",
      "You Belong With Me",
      "You're Not Sorry",
      "All You Had To Do Was Stay",
      "Bad Blood",
      "Blank Space",
      "august",
      "betty",
      "cardigan",
      "Anti-Hero",
      "Bejeweled",
      "Bigger Than The Whole Sky",
    ],
  },

  {
    bingoItem: "Reference to her family and friends",
    type: "Misc",
    listOfMusics: ["Fifteen", "The Best Day", "22"],
  },
  {
    bingoItem: "Surprise song on The Era's Tour",
    type: "Misc",
    listOfMusics: ["The Moment I Knew", "Dress", "So It Goes...", "Maroon"],
  },
  {
    bingoItem: "2:00 AM",
    type: "Misc",
    listOfMusics: ["Breathe", "I Wish You Would"],
  },
  {
    bingoItem: "Debut album",
    type: "Misc",
    listOfMusics: [
      "Tim McGraw",
      "Picture To Burn",
      "A Place In This World",
      "Cold As You",
      "The Outside",
      "Stay Beautiful",
      "Should’ve Said No",
      "Mary’s Song (Oh My My My)",
      "Our Song",
      "I’m Only Me When I’m With You",
      "Invisible",
      "A Perfectly Good Heart",
      "Teardrops on My Guitar",
      "I Heart ?",
    ],
  },
  {
    bingoItem: "Lyrics about New York",
    type: "Songs about...",
    listOfMusics: [
      "Welcome to New York",
      "Cornelia Street",
      "Maroon",
      "Holy Ground",
      "Come back... Be here",
      "The Lucky One",
    ],
  },
  {
    bingoItem: "Mention of a specific time",
    type: "Songs about...",
    listOfMusics: ["Out of the Woods", "Treacherous", "Wildest Dreams"],
  },
  {
    bingoItem: "Mention of rain",
    type: "Songs about...",
    listOfMusics: ["Come in with the Rain", "Forever & Always"],
  },
  {
    bingoItem: "Mention of a car or driving",
    type: "Songs about...",
    listOfMusics: ["Getaway Car", "Fearless", "Picture to Burn"],
  },
  {
    bingoItem: "Break-up",
    type: "Songs about...",
    listOfMusics: [
      "We Are Never Ever Getting Back Together",
      "Back to December",
      "All Too Well",
    ],
  },
  {
    bingoItem: "Cheating",
    type: "Songs about...",
    listOfMusics: ["The Other Side of The Door", "Picture to Burn"],
  },
  {
    bingoItem: "Fall in love",
    type: "Songs about...",
    listOfMusics: ["Lover", "Enchanted", "Fearless"],
  },
];

module.exports = data;
